import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../app/globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer";
import { Toaster } from 'react-hot-toast';
import 'aos/dist/aos.css'; // Import AOS styles globally
import AosInit from "./components/AosInit";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chronicles of Stranger",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic"; // <- Add this line

 export default function RootLayout({ children }: { children: React.ReactNode }) {
 const data = { mode: false };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        <AosInit />
        {data?.mode ?  (
          <main className="flex justify-center items-center min-h-screen text-white">
            <p>Site is currently under maintenance.</p>
          </main>
        ):(
          <>
            <Header />
            <main className="w-full flex justify-center ">
              <div className="w-full p-0 max-w-[1600px]" data-aos="fade-in">
                <Toaster position="top-center" />
                {children}
              </div>
            </main>
            <Footer />
          </>
        ) }
      </body>
    </html>
  );
}
