import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chronicles of Strainger",
  description: "Generated by create next app",
};
 export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let data = { mode: false };

  try {
    const res = await fetch('http://localhost:3000/api/maintenance', { method: 'GET', cache: 'no-store' });
    if (res.ok) {
      const jsonData = await res.json();
      data = jsonData.maintenance|| {};
      console.log(data);
    }
  } catch (error) {
    console.error('Maintenance status fetch failed:', error);
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        
        {data?.mode ?  (
          <main className="flex justify-center items-center min-h-screen text-white">
           
            <p>Site is currently under maintenance.</p>
          </main>
        ):(
          <>
            <Header />
            <main className="w-full flex justify-center">
              <div className="w-full p-0">
                <Toaster position="top-center" />
                {children}
              </div>
            </main>
            <Footer />
          </>
        ) }
      </body>
    </html>
  );
}
