interface Country{
  id:number,
  code:string,
  name:string
} 

export const countries: Country[] = [
    { "id": 1, "code": "AF", "name": "Afghanistan" },
    { "id": 2, "code": "AL", "name": "Albania" },
    { "id": 3, "code": "DZ", "name": "Algeria" },
    { "id": 4, "code": "AD", "name": "Andorra" },
    { "id": 5, "code": "AO", "name": "Angola" },
    { "id": 6, "code": "AG", "name": "Antigua and Barbuda" },
    { "id": 7, "code": "AR", "name": "Argentina" },
    { "id": 8, "code": "AM", "name": "Armenia" },
    { "id": 9, "code": "AU", "name": "Australia" },
    { "id": 10, "code": "AT", "name": "Austria" },
    { "id": 11, "code": "AZ", "name": "Azerbaijan" },
    { "id": 12, "code": "BS", "name": "Bahamas" },
    { "id": 13, "code": "BH", "name": "Bahrain" },
    { "id": 14, "code": "BD", "name": "Bangladesh" },
    { "id": 15, "code": "BB", "name": "Barbados" },
    { "id": 16, "code": "BY", "name": "Belarus" },
    { "id": 17, "code": "BE", "name": "Belgium" },
    { "id": 18, "code": "BZ", "name": "Belize" },
    { "id": 19, "code": "BJ", "name": "Benin" },
    { "id": 20, "code": "BT", "name": "Bhutan" },
    { "id": 21, "code": "BO", "name": "Bolivia" },
    { "id": 22, "code": "BA", "name": "Bosnia and Herzegovina" },
    { "id": 23, "code": "BW", "name": "Botswana" },
    { "id": 24, "code": "BR", "name": "Brazil" },
    { "id": 25, "code": "BN", "name": "Brunei" },
    { "id": 26, "code": "BG", "name": "Bulgaria" },
    { "id": 27, "code": "BF", "name": "Burkina Faso" },
    { "id": 28, "code": "BI", "name": "Burundi" },
    { "id": 29, "code": "CV", "name": "Cabo Verde" },
    { "id": 30, "code": "KH", "name": "Cambodia" },
    { "id": 31, "code": "CM", "name": "Cameroon" },
    { "id": 32, "code": "CA", "name": "Canada" },
    { "id": 33, "code": "CF", "name": "Central African Republic" },
    { "id": 34, "code": "TD", "name": "Chad" },
    { "id": 35, "code": "CL", "name": "Chile" },
    { "id": 36, "code": "CN", "name": "China" },
    { "id": 37, "code": "CO", "name": "Colombia" },
    { "id": 38, "code": "KM", "name": "Comoros" },
    { "id": 39, "code": "CG", "name": "Congo" },
    { "id": 40, "code": "CD", "name": "Democratic Republic of the Congo" },
    { "id": 41, "code": "CR", "name": "Costa Rica" },
    { "id": 42, "code": "HR", "name": "Croatia" },
    { "id": 43, "code": "CU", "name": "Cuba" },
    { "id": 44, "code": "CY", "name": "Cyprus" },
    { "id": 45, "code": "CZ", "name": "Czech Republic" },
    { "id": 46, "code": "CI", "name": "Côte d'Ivoire" },
    { "id": 47, "code": "DK", "name": "Denmark" },
    { "id": 48, "code": "DJ", "name": "Djibouti" },
    { "id": 49, "code": "DM", "name": "Dominica" },
    { "id": 50, "code": "DO", "name": "Dominican Republic" },
    { "id": 51, "code": "EC", "name": "Ecuador" },
    { "id": 52, "code": "EG", "name": "Egypt" },
    { "id": 53, "code": "SV", "name": "El Salvador" },
    { "id": 54, "code": "GQ", "name": "Equatorial Guinea" },
    { "id": 55, "code": "ER", "name": "Eritrea" },
    { "id": 56, "code": "EE", "name": "Estonia" },
    { "id": 57, "code": "SZ", "name": "Eswatini" },
    { "id": 58, "code": "ET", "name": "Ethiopia" },
    { "id": 59, "code": "FJ", "name": "Fiji" },
    { "id": 60, "code": "FI", "name": "Finland" },
    { "id": 61, "code": "FR", "name": "France" },
    { "id": 62, "code": "GA", "name": "Gabon" },
    { "id": 63, "code": "GM", "name": "Gambia" },
    { "id": 64, "code": "GE", "name": "Georgia" },
    { "id": 65, "code": "DE", "name": "Germany" },
    { "id": 66, "code": "GH", "name": "Ghana" },
    { "id": 67, "code": "GR", "name": "Greece" },
    { "id": 68, "code": "GD", "name": "Grenada" },
    { "id": 69, "code": "GT", "name": "Guatemala" },
    { "id": 70, "code": "GN", "name": "Guinea" },
    { "id": 71, "code": "GW", "name": "Guinea-Bissau" },
    { "id": 72, "code": "GY", "name": "Guyana" },
    { "id": 73, "code": "HT", "name": "Haiti" },
    { "id": 74, "code": "HN", "name": "Honduras" },
    { "id": 75, "code": "HU", "name": "Hungary" },
    { "id": 76, "code": "IS", "name": "Iceland" },
    { "id": 77, "code": "IN", "name": "India" },
    { "id": 78, "code": "ID", "name": "Indonesia" },
    { "id": 79, "code": "IR", "name": "Iran" },
    { "id": 80, "code": "IQ", "name": "Iraq" },
    { "id": 81, "code": "IE", "name": "Ireland" },
    { "id": 82, "code": "IL", "name": "Israel" },
    { "id": 83, "code": "IT", "name": "Italy" },
    { "id": 84, "code": "JM", "name": "Jamaica" },
    { "id": 85, "code": "JP", "name": "Japan" },
    { "id": 86, "code": "JO", "name": "Jordan" },
    { "id": 87, "code": "KZ", "name": "Kazakhstan" },
    { "id": 88, "code": "KE", "name": "Kenya" },
    { "id": 89, "code": "KI", "name": "Kiribati" },
    { "id": 90, "code": "KP", "name": "North Korea" },
    { "id": 91, "code": "KR", "name": "South Korea" },
    { "id": 92, "code": "KW", "name": "Kuwait" },
    { "id": 93, "code": "KG", "name": "Kyrgyzstan" },
    { "id": 94, "code": "LA", "name": "Laos" },
    { "id": 95, "code": "LV", "name": "Latvia" },
    { "id": 96, "code": "LB", "name": "Lebanon" },
    { "id": 97, "code": "LS", "name": "Lesotho" },
    { "id": 98, "code": "LR", "name": "Liberia" },
    { "id": 99, "code": "LY", "name": "Libya" },
    { "id": 100, "code": "LI", "name": "Liechtenstein" },
    { "id": 101, "code": "LT", "name": "Lithuania" },
    { "id": 102, "code": "LU", "name": "Luxembourg" },
    { "id": 103, "code": "MG", "name": "Madagascar" },
    { "id": 104, "code": "MW", "name": "Malawi" },
    { "id": 105, "code": "MY", "name": "Malaysia" },
    { "id": 106, "code": "MV", "name": "Maldives" },
    { "id": 107, "code": "ML", "name": "Mali" },
    { "id": 108, "code": "MT", "name": "Malta" },
    { "id": 109, "code": "MH", "name": "Marshall Islands" },
    { "id": 110, "code": "MR", "name": "Mauritania" },
    { "id": 111, "code": "MU", "name": "Mauritius" },
    { "id": 112, "code": "MX", "name": "Mexico" },
    { "id": 113, "code": "FM", "name": "Micronesia" },
    { "id": 114, "code": "MD", "name": "Moldova" },
    { "id": 115, "code": "MC", "name": "Monaco" },
    { "id": 116, "code": "MN", "name": "Mongolia" },
    { "id": 117, "code": "ME", "name": "Montenegro" },
    { "id": 118, "code": "MA", "name": "Morocco" },
    { "id": 119, "code": "MZ", "name": "Mozambique" },
    { "id": 120, "code": "MM", "name": "Myanmar" },
    { "id": 121, "code": "NA", "name": "Namibia" },
    { "id": 122, "code": "NR", "name": "Nauru" },
    { "id": 123, "code": "NP", "name": "Nepal" },
    { "id": 124, "code": "NL", "name": "Netherlands" },
    { "id": 125, "code": "NZ", "name": "New Zealand" },
    { "id": 126, "code": "NI", "name": "Nicaragua" },
    { "id": 127, "code": "NE", "name": "Niger" },
    { "id": 128, "code": "NG", "name": "Nigeria" },
    { "id": 129, "code": "MK", "name": "North Macedonia" },
    { "id": 130, "code": "NO", "name": "Norway" },
    { "id": 131, "code": "OM", "name": "Oman" },
    { "id": 132, "code": "PK", "name": "Pakistan" },
    { "id": 133, "code": "PW", "name": "Palau" },
    { "id": 134, "code": "PS", "name": "Palestine" },
    { "id": 135, "code": "PA", "name": "Panama" },
    { "id": 136, "code": "PG", "name": "Papua New Guinea" },
    { "id": 137, "code": "PY", "name": "Paraguay" },
    { "id": 138, "code": "PE", "name": "Peru" },
    { "id": 139, "code": "PH", "name": "Philippines" },
    { "id": 140, "code": "PL", "name": "Poland" },
    { "id": 141, "code": "PT", "name": "Portugal" },
    { "id": 142, "code": "QA", "name": "Qatar" },
    { "id": 143, "code": "RO", "name": "Romania" },
    { "id": 144, "code": "RU", "name": "Russia" },
    { "id": 145, "code": "RW", "name": "Rwanda" },
    { "id": 146, "code": "KN", "name": "Saint Kitts and Nevis" },
    { "id": 147, "code": "LC", "name": "Saint Lucia" },
    { "id": 148, "code": "VC", "name": "Saint Vincent and the Grenadines" },
    { "id": 149, "code": "WS", "name": "Samoa" },
    { "id": 150, "code": "SM", "name": "San Marino" },
    { "id": 151, "code": "ST", "name": "Sao Tome and Principe" },
    { "id": 152, "code": "SA", "name": "Saudi Arabia" },
    { "id": 153, "code": "SN", "name": "Senegal" },
    { "id": 154, "code": "RS", "name": "Serbia" },
    { "id": 155, "code": "SC", "name": "Seychelles" },
    { "id": 156, "code": "SL", "name": "Sierra Leone" },
    { "id": 157, "code": "SG", "name": "Singapore" },
    { "id": 158, "code": "SK", "name": "Slovakia" },
    { "id": 159, "code": "SI", "name": "Slovenia" },
    { "id": 160, "code": "SB", "name": "Solomon Islands" },
    { "id": 161, "code": "SO", "name": "Somalia" },
    { "id": 162, "code": "ZA", "name": "South Africa" },
    { "id": 163, "code": "SS", "name": "South Sudan" },
    { "id": 164, "code": "ES", "name": "Spain" },
    { "id": 165, "code": "LK", "name": "Sri Lanka" },
    { "id": 166, "code": "SD", "name": "Sudan" },
    { "id": 167, "code": "SR", "name": "Suriname" },
    { "id": 168, "code": "SE", "name": "Sweden" },
    { "id": 169, "code": "CH", "name": "Switzerland" },
    { "id": 170, "code": "SY", "name": "Syria" },
    { "id": 171, "code": "TJ", "name": "Tajikistan" },
    { "id": 172, "code": "TZ", "name": "Tanzania" },
    { "id": 173, "code": "TH", "name": "Thailand" },
    { "id": 174, "code": "TL", "name": "Timor-Leste" },
    { "id": 175, "code": "TG", "name": "Togo" },
    { "id": 176, "code": "TO", "name": "Tonga" },
    { "id": 177, "code": "TT", "name": "Trinidad and Tobago" },
    { "id": 178, "code": "TN", "name": "Tunisia" },
    { "id": 179, "code": "TR", "name": "Turkey" },
    { "id": 180, "code": "TM", "name": "Turkmenistan" },
    { "id": 181, "code": "TV", "name": "Tuvalu" },
    { "id": 182, "code": "UG", "name": "Uganda" },
    { "id": 183, "code": "UA", "name": "Ukraine" },
    { "id": 184, "code": "AE", "name": "United Arab Emirates" },
    { "id": 185, "code": "GB", "name": "United Kingdom" },
    { "id": 186, "code": "US", "name": "United States" },
    { "id": 187, "code": "UY", "name": "Uruguay" },
    { "id": 188, "code": "UZ", "name": "Uzbekistan" },
    { "id": 189, "code": "VU", "name": "Vanuatu" },
    { "id": 190, "code": "VA", "name": "Vatican City" },
    { "id": 191, "code": "VE", "name": "Venezuela" },
    { "id": 192, "code": "VN", "name": "Vietnam" },
    { "id": 193, "code": "YE", "name": "Yemen" },
    { "id": 194, "code": "ZM", "name": "Zambia" },
    { "id": 195, "code": "ZW", "name": "Zimbabwe" }
  ]
 export default countries;
