// app/layout.js
import Preloader from "./components/Preloader";
import "./page.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "animate.css/animate.min.css";
import Footer from "./components/Footer";
import './../../src/app/globals.css';
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader>
         <main style={{}}>
         <Header/>
          <div className="container">
            <div className="row"></div>
            {children}
          </div>
          <Footer/>
         </main>
          </Preloader>
      </body>
    </html>
  );
}